# Generated by Django 4.1.7 on 2023-03-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATCadmin', '0002_rename_employees_auth_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='auth_user',
            new_name='Users',
        ),
    ]
